### ISSUE TITLE
Add "Edit Hosts File"

### ISSUE THREAD

**Issue by randycasburn** [lanayotech/vagrant-manager#114]
A feature request to simply open the default hosts file in the default text editor. This is a convenience feature request.

**Comment by chriswayoub** [comment]
This feature has been added in version 2.5.0. Unfortunately, we were not able to open the hosts file in the default text editor automatically due to permission issues (the file is owned by root), so it opens in terminal using sudo. There is a new preference to choose either nano or vim as the editor.

**Comment by randycasburn** [comment]
Thanks Chris!!
