### ISSUE TITLE
2.5.0 keeps refreshing

### ISSUE THREAD

**Issue by jenssegers** [lanayotech/vagrant-manager#118]
I updated to 2.5.0 and now my vagrant manager is stuck on 'Refreshing...'. It is not even showing my old boxes anymore.

**Comment by jenssegers** [comment]
I found these entries in my console:

```
14/10/15 16:20:34,259 Vagrant Manager[56745]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
14/10/15 16:20:34,892 Vagrant Manager[56745]: assertion failed: 15A284: libxpc.dylib + 79134 [3E09C275-A33B-357A-B0AB-A2DDF88EC9D5]: 0x89
```

**Comment by jenssegers** [comment]
Strange, tried downgrading to 2.4 and it is still stuck on 'Refreshing...'.

**Comment by amitailanciano** [comment]
Try checking the Preferences window and making sure your Refresh interval isn't set too low for your system to handle?

**Comment by jenssegers** [comment]
I didn't enable it.

**Comment by chriswayoub** [comment]
What version of OS X are you running?

**Comment by jenssegers** [comment]
El Capitan

**Comment by colinhoernig** [comment]
I'm also noticing the constant refreshing.  I have Vagrant Manager set to load on system start, which is when it constantly refreshes.  If I kill the app and then restart it, it will then find the bookmarked Vagrant boxes as expected.  The "Refresh every {x}" setting is not enabled.

**Comment by StefanoCecere** [comment]
my setup (same as colin: OS X 10.10.5, Vagrant 1.7.4. All of my boxes are Virtualbox VMs ) doenst work anymore. i was using v 2.5
since a few days it keeps refreshing.. very strange.
even downgrading to 2.4.4 doesn't fix

**Comment by amitailanciano** [comment]
Sorry we've been busy lately, we'll try to put out a debug version to get some information here pretty soon

**Comment by ryanaltvater** [comment]
I am also on El Capitan and just installed 2.5.1 after having reformatted my MacBook in the last week. My issue is kind of similar? Maybe it's just feedback about the refresh interval feature. Before I went through the reformat process, Vagrant Manager would auto-refresh after I had run "vagrant up". I'm unsure what version I had previously. Currently, it doesn't auto-refresh anymore and I have to enable the preference to auto-refresh every specified interval. Was this changed on purpose? I prefer Vagrant Manager auto-refreshing after the "vagrant up" process has finished and that's it, rather than constantly refreshing on its own when it doesn't need to. I can't say that I'm personally in need of the feature, but I don't want to have to manually refresh either. I've been using the VM count as a real-time indicator of VMs that are up and running, when I'm switching from project to project. If the refresh interval preference is too short, my MacBook starts to scream. If the interval is too long, then it's delayed and can be confusing when it shows or doesn't show a VM is up and running when I performed a vagrant action a while ago. Would it be possible to include another preference checkbox to only do a refresh after a vagrant process has finished?

**Comment by jacobgraf** [comment]
I am also having this issue. Really weird and definitely frustrating.

**Comment by amitailanciano** [comment]
@jacobgraf are you still experiencing this issue with the latest vagrant & vagrant-manager builds?

**Comment by StefanoCecere** [comment]
i've never seen this problem anymore since a loong time!

**Comment by amitailanciano** [comment]
thanks @StefanoCecere, I'm going to close this then
