### ISSUE TITLE
Vagrantmanager writes logfiles en masse

### ISSUE THREAD

**Issue by esszett** [lanayotech/vagrant-manager#123]
Vagrant Manager 2.5.0, OS X El Capitan 10.11.1 - as soon as I enable preferences "Refresh every [15s]" vm writes logfile/s in ~user/Library/Logs/VMware/. It's complaining on missing VMware config file(?). Please see attached. 

Vmware Fusion 8.0.2, Vagrant 1.7.4 (vagrant-vmware-fusion (4.0.2), vagrant-bindfs (0.4.3), vagrant-share (1.1.4, system)).
I just deleted 80.000 files…

[vmware-vix-49007-log.txt](https://github.com/lanayotech/vagrant-manager/files/49875/vmware-vix-49007-log.txt)

**Comment by chriswayoub** [comment]
This is interesting, we don't actually do anything with VMWare directly. We run vagrant global-status, scan the NFS exports, query VirtualBox, and query Parallels. Can you see if log files are created when you run vagrant global-status on its own?

**Comment by esszett** [comment]
There are no logs produced while running vagrant global-status directly…

**Comment by amitailanciano** [comment]
@esszett is this still an issue with the latest vagrant & vagrant manager?

**Comment by esszett** [comment]
Still same issue - running vagrant 1.92, vagrant manager 2.5.4, vmwarefusion 8.5.3, vagrant-vmware-fusion (4.0.15) on OS X 10.11.6. 
Disabling the "refresh every 15sec" setting stops the permanent log-entries.

**Comment by chriswayoub** [comment]
I don't think Vagrant Manager is doing anything special to cause these logs. The only thing we run would be `vagrant global-status`. Do the log files get created when you run that as well? I'm guessing this log file is created even without Vagrant Manager, but the name probably has the PID in it, and since we run the refresh in it's own process it keeps creating new files instead of writing to the same one. This is just a guess though, and I don't think there is anything we can do to fix this on our end.
