### ISSUE TITLE
Windows should be at top/foreground

### ISSUE THREAD

**Issue by mblaschke** [lanayotech/vagrant-manager#124]
Most of the time all windows of Vagrant Manager are hiding below some windows (eg. for destroy or up).

OS: os x el capitan
Vagrant Manager: 2.5.0

**Comment by chriswayoub** [comment]
Since the app is an agent app (it doesn't have a main UI), I think it's causing issues sometimes when presenting windows. We're considering solutions, but the best one we've found so far is to not make it an agent app which means it will always show an icon in the dock. Clicking on the dock icon would do nothing, since there is no main window to display, so we are trying to come up with the most acceptable solution for this.

**Comment by chriswayoub** [comment]
This feature has been implemented in the [latest release](https://github.com/lanayotech/vagrant-manager/releases/tag/2.6.0)
