### ISSUE TITLE
Mac OS X - "Vagrant Manager.app" can't be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by clementblanco** [lanayotech/vagrant-manager#141]
Hi,
I'm a user from an Active Directory and my profile doesn't allow me to allow "un-trusted" developers from the security settings on my Mac.
Could you please become an "identified developer"?
Thanks.

![screen shot on 2016-06-07 at 08-42-45](https://cloud.githubusercontent.com/assets/668419/15849801/2721ee50-2c8c-11e6-977c-809902d42ec2.png)
![screen shot on 2016-06-07 at 08-40-30](https://cloud.githubusercontent.com/assets/668419/15849803/2a2ab870-2c8c-11e6-8090-ae7ab9798f5d.png)

**Comment by michaeldhopkins** [comment]
Hi, this is still an issue with Vagrant 1.9.2 on MacOS 10.12.3. I don't think Vagrant has always been this way; is it a regression in the .pkg builder?

![screen shot 2017-03-03 at 12 54 28 pm](https://cloud.githubusercontent.com/assets/133994/23564721/ad88f58a-0010-11e7-8a87-33b049b634cf.png)

**Comment by martin-hewitt** [comment]
I get this error when trying to install Vagrant 1.9.2 on MacOS 10.12.3, downloaded from the main Vagrant download page.

I do not see it when trying to install 1.9.1, downloaded from the "Older versions" page.

**Comment by amitailanciano** [comment]
In order to eliminate this warning, we would need to pay for an Apple Developer Program license, which we have no plans to do at this time.

This project/software is completely open source and free to use, and our company name is present here in this repo and in the software itself. If you have concerns about safety or risk to your device, you're free to inspect the source code and/or compile the application yourself on your own device. Keep in mind that this software is governed by the [MIT license](https://github.com/lanayotech/vagrant-manager/blob/develop/LICENSE.md) and therefore is provided as-is, without warranty of any kind.

If you're not sure how to run this program despite the warning, you can do so by navigating to Security & Privacy in System Preferences, and clicking "Allow" in the section towards the bottom.
