### ISSUE TITLE
Support multi-machine vagrants. 

### ISSUE THREAD

**Issue by octalmage** [lanayotech/vagrant-manager#146]
Currently this tool doesn't seem to (fully?) support [multi-machine](https://www.vagrantup.com/docs/multi-machine/) vagrants. It shows that it is always off, and I can't "up" the individual boxes. It would be cool if I could select with machines to bring up, and see the status of each box. 

Thanks!

**Comment by mklemm2** [comment]
Strange, I can do all of that.

<img width="466" alt="screenshot_18_08_16__10_05" src="https://cloud.githubusercontent.com/assets/17253314/17762160/8b4dfe6e-652b-11e6-85cb-7bd7040c2bea.png">

**Comment by octalmage** [comment]
What? That looks amazing! I wonder what could be wrong on my end.

**Comment by andrew40** [comment]
Ermmm how do you do that? Thats something that might be useful to me?

**Comment by chriswayoub** [comment]
@octalmage can you provide a stripped down Vagrantfile that causes issues for you so that I can test the same file on my end? Multi-machine boxes should work properly, can you provide any more details about what exactly is happening in your case? Can you also provide the version of Vagrant and Vagrant Manager that you are running?

**Comment by octalmage** [comment]
Of course! Give me a bit to get everything together. There's a ton in my Vagrant file and stripping it down could resolve the issue. I'll let you know!
