### ISSUE TITLE
OSX: Auto detect only if folder name is "vagrant"

### ISSUE THREAD

**Issue by canemacchina** [lanayotech/vagrant-manager#147]
I don't understand one thing: why Vagrant Manager auto detect my instances only if the Vagrantfile is into a folder named "vagrant"?

I mean, I have a folder named "vagrant", and Vagrant manager find an instance inside it. Then if I rename that folder to "foo" and refresh Vagrant Manager, it doesn't auto detect again the instance.

**Comment by i90rr** [comment]
I'm experiencing the exactly same behavior on Sierra 10.12.6, Vagrant 2 installed via Brew and Vagrant Manager 2.5.4 installed using the provided DMG from the Releases section.

**Comment by chriswayoub** [comment]
The issue here is that we need to be able to find the path to the Vagrantfile using one of the following methods:
* a bookmark you've added to Vagrant Manager
* looking at the output of "vagrant global-status"
* looking at your /etc/exports file

In all 3 of those cases, if you rename the folder then none of those methods will be pointing to your Vagrantfile anymore. They are all pointing at the old folder name. There isn't any way for us to find your Vagrantfile without scanning your whole drive, and that's too resource intensive to do on a regular basis. If you use the option to recursively scan for machines in the Manage Bookmarks window then it will find your Vagrantfile in the new folder, or you can up it at least once from the command line so that one of the detection methods mentioned above will work.
