### ISSUE TITLE
Can't up vmware_desktop boxes

### ISSUE THREAD

**Issue by pixelwatt** [lanayotech/vagrant-manager#173]
First off, this project is awesome! In terms of the issue, vmware boxes recently started using vmware_desktop as the provider, so when Vagrant Manager tries to boot the VM with vmware_fusion or vmware_workstation, the up command fails. Can vmware_desktop be added as a provider choice?

**Comment by amitailanciano** [comment]
Absolutely, we'll make sure to add it to the default list in the next release.

I also think it probably makes sense to allow users to manage the list of available providers themselves, since you can have [custom providers](https://www.vagrantup.com/docs/providers/custom.html). We'll add a place to do this in the next release as well.

**Comment by amitailanciano** [comment]
this will be included in the next release
