### ISSUE TITLE
Asking permission to use microphone?

### ISSUE THREAD

**Issue by chrispage1** [lanayotech/vagrant-manager#175]
Hi,

I've installed vagrant manager on Mac OS Mojave and its asking for permission to use the microphone. Just wondering why it would need permission to the mic?

Chris.

**Comment by chriswayoub** [comment]
This is actual from VirtualBox (or possibly whatever VM provider you are using). Since Vagrant Manager owns the process that run the Vagrant commands, it requests that permission through Vagrant Manager when the box is launching.

If you launch a box directly from VirtualBox you should see the same prompt (if you haven't previously granted permission).

[There is some discussion about the same issue here](https://discourse.roots.io/t/why-does-vagrant-up-require-use-of-microphone/14111/4)
> Just disable audio directly on Virtualbox: VM Settings > audio > Uncheck "Enable Audio".
