### ISSUE TITLE
For some reason I have a vagrant box that appears twice.

### ISSUE THREAD

**Issue by cooperaj** [lanayotech/vagrant-manager#63]
I have a vagrant box on my machine (verified to be a single machine via "vagrant global-status") that appears twice in my Vagrant Manager window. 

The folder on my host that the machine lives in is called "CLiC". This appears in the vagrant manager menu. I also see a "clic". Both menu items appear to control the same machine though there is a good chance that one of them will report the opposite status to the other.

https://www.dropbox.com/s/9ubehn6fhx7zo38/Screenshot%202015-01-21%2011.46.28.png?dl=0

**Comment by chriswayoub** [comment]
Can you try choose "Open in Finder" from both of them? Do they both open the same exact folder on your system? It indexes the discovered machines based on their path, so it shouldn't be able to detect it twice if the machine is in the same folder. I'm trying to think of how this could be possible, but nothing comes to mind. We can put together a debug build to get some more troubleshooting info from you if we need to.

**Comment by chriswayoub** [comment]
It looks like this is caused by the default settings in Terminal, and I haven't found a reliable workaround that doesn't cause other issues. You can see an explanation in this forum post:
http://www.alfredforum.com/topic/1291-terminal-action-repeats-when-opening-new-tabs/

> OS X's default is that New tabs open with: Same Settings. This means that if, for example, you began a terminal session by SSH'ing into another machine, a new tab will also attempt to SSH into that machine. To alleviate this behavior, switch it to Default Settings.
> ![ztvedw](https://cloud.githubusercontent.com/assets/1111667/5987098/fbbccdb4-a8d6-11e4-90f5-bd1f2196f5dc.png)

The AppleScript support is pretty poor in Terminal, I'd recommend using [iTerm2](http://iterm2.com/) and setting that as your preferred terminal in Vagrant Manager.

**Comment by chriswayoub** [comment]
Did you happen to rename the folder your Vagrant machine is in? I was able to recreate this by renaming the folder that my Vagrant machine was in to the same folder name with different capitalization. The vagrant global-status command still shows the folder as the original capitalization, but Vagrant Manager detects it with the new capitalization and regards it as a different path. We have looked into a few solutions, but none of them are straightforward. The filesystem can be case-sensitive or case-insensitive, so we can't assume it is the same path. We also looked into comparing inodes of the two paths, but inodes can be identical if they are on different file systems so that would require changes to the core of how we detect Vagrant machines.

I don't think there is a fix that we will be implementing for this issue right now, but we would welcome a pull request that addresses it.

**Comment by cooperaj** [comment]
@chriswayoub Yep. I think thats what I did. Sort of. Deleted it and rechecked it out of git with a differently capitalised name. It seems to have resolved itself now. I'm not sure what I did. I believe I deleted the .vagrant folder after running a vagrant destroy but that was a while ago now and I can't be sure.
