### ISSUE TITLE
After using "SSH" command in Vagrant Manager new terminal tabs always try to connect

### ISSUE THREAD

**Issue by bonny** [lanayotech/vagrant-manager#66]
Before starting vagrant manager, when i press CMD+T in a terminal window a new terminal tab opens, just like it always does.

However, after going to Vagrant Manager and selecting my vagrant and then choosing "SSH",
a new terminal tab opens and `cd` to the folder of the vagrant and does a `vagrant ssh`. So far so good. 

However: If I now press CMD+T again in the terminal window, a new terminal tab opens, but it does always do the cd vagrant dir + vagrant ssh-thingie. I must quit the terminal to get old behavior back. I expect my terminal to only go to the vagrant dir + start ssh after choosing it in the meny, not always.

**Comment by chriswayoub** [comment]
I've duplicated this bug on my machine and will look into a solution.

**Comment by chriswayoub** [comment]
It looks like this is caused by the default settings in Terminal, and I haven't found a reliable workaround that doesn't cause other issues. You can see an explanation in this forum post:
http://www.alfredforum.com/topic/1291-terminal-action-repeats-when-opening-new-tabs/

> OS X's default is that New tabs open with: Same Settings. This means that if, for example, you began a terminal session by SSH'ing into another machine, a new tab will also attempt to SSH into that machine. To alleviate this behavior, switch it to Default Settings.
> ![ztvedw](https://cloud.githubusercontent.com/assets/1111667/5987098/fbbccdb4-a8d6-11e4-90f5-bd1f2196f5dc.png)

The AppleScript support is pretty poor in Terminal, I'd recommend using [iTerm2](http://iterm2.com/) and setting that as your preferred terminal in Vagrant Manager.
