### ISSUE TITLE
Name in list is name of parent folder and not VM?

### ISSUE THREAD

**Issue by marcusmoore88** [lanayotech/vagrant-manager#96]
The name of a machine in VirtualBox is displayed correctly but in Vagrant Manager it seems like it uses the name of the parent folder where the Vagrantfile lives?

Is this expected or a bug? I would have expected the name in VirtualBox to be the same name that is the Vagrant Manager list.

**Comment by amitailanciano** [comment]
I suppose it is a little strange, but that's just how Vagrant Manager has always worked.. it was originally an in house app, and our workflows generally involve creating a folder with the project name and a Vagrantfile at the root of it. There _is_ an option in the preferences to append the actual box names in parens beside the folder name, so that might be something you'd like to enable
